jobs:
  create_issue:
    permissions:
      contents: read
      issues: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: dlversion
      name: Get downloadable version
      run: 'RandNum=$((1 + $RANDOM % 5000))

        curl -H "Accept-Encoding: identity" -H "Accept-Language: en" -L -A "Mozilla/5.0
        (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.$RandNum.212
        Safari/537.36" -o $HOME/version.html https://www.minecraft.net/en-us/download/server/bedrock

        LatestURL=$(grep -o ''https://minecraft.azureedge.net/bin-linux/[^"]*'' $HOME/version.html)

        echo "::set-output name=downloadversion::$(echo "$LatestURL" | sed -e ''s/.*server-//g''
        -e ''s/.zip//'')"

        '
    - continue-on-error: true
      id: dlversionnotes
      name: Get Release Notes
      run: 'RandNum=$((1 + $RANDOM % 5000))

        curl -H "Accept-Encoding: identity" -H "Accept-Language: en" -L -A "Mozilla/5.0
        (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.$RandNum.212
        Safari/537.36" -o $HOME/hc.html https://feedback.minecraft.net/api/v2/help_center/en-us/sections/360001186971/articles

        titleversion=$(echo "${{ steps.dlversion.outputs.downloadversion }}" | sed
        -r ''s/([0-9]*)\.([0-9]*)\.([0-9]*)\.([0-9]*)/\1-\2-\3/g'')

        echo "::set-output name=downloadversionnotes::$(grep -o ''https://feedback.minecraft.net/hc/en-us/articles/[^"]*''${titleversion}''[^"]*''
        $HOME/hc.html)"

        '
    - continue-on-error: true
      name: Checkout repo
      uses: actions/checkout@v3
    - continue-on-error: true
      id: suppversion
      name: Latest supported version from repo
      run: echo "::set-output name=supportversion::$(cat .github/assets/supportedVersion)"
    - continue-on-error: true
      id: check_if_issue_exists
      name: Check if Issue Exists
      uses: nickderobertis/check-if-issue-exists-action@master
      with:
        labels: enhancement
        repo: Pugmatt/BedrockConnect
        title: New Bedrock Version ${{ steps.dlversion.outputs.downloadversion }}
          has been published!
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      if: ${{ steps.check_if_issue_exists.outputs.exists == 'false' && steps.dlversion.outputs.downloadversion
        != steps.suppversion.outputs.supportversion }}
      name: Create an issue
      uses: actions-ecosystem/action-create-issue@v1
      with:
        body: '## New Bedrock Version ${{ steps.dlversion.outputs.downloadversion
          }}


          Release Notes: ${{ steps.dlversionnotes.outputs.downloadversionnotes }}


          - [X] Notify @Pugmatt @kmpoppe @Camotoy @CrafterPika

          - [ ] Update source code

          - [ ] Update [.github/assets/supportedVersion](../blob/master/.github/assets/supportedVersion)
          to the latest version

          '
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: 'enhancement

          '
        title: New Bedrock Version ${{ steps.dlversion.outputs.downloadversion }}
          has been published!
name: Check for new version every hour
on:
  repository_dispatch:
    types: trigger-ga___checkversion.yml
