jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      name: Build with maven
      run: 'cd serverlist-server

        mvn -B package --file pom.xml

        '
    - continue-on-error: true
      name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: ./serverlist-server/target/BedrockConnect-1.0-SNAPSHOT.jar
name: buildroot
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
